//
//  CoupageCLI.swift
//  CYaml
//
//  Created by kota-otsu on 2019/03/06.
//

import Foundation
import Config
import ConfigLoader
import TemplateLoader
import PageGenerator

public struct CoupageCLI {

    public struct Parameter {
        let title: String
        let spaceKey: String?
        let ancestorsKey: String?
        let templateAuguments: [String: String]
        
        public init(title: String, spaceKey: String?, ancestorsKey: String?, templateAuguments: [String: String]){
            self.title = title
            self.spaceKey = spaceKey
            self.ancestorsKey = ancestorsKey
            self.templateAuguments = templateAuguments
        }
    }
    
    public static func execute(_ parameter: Parameter) {

        let spaceKey = parameter.spaceKey
        let ancestorsKey = parameter.ancestorsKey

        let config = ConfigLoader.loadConfig()
        let template = TemplateLoader.fetchTemplate()

        let confluence = Config.Confluence(url: config.confluence.url,
                                           spaceKey: spaceKey ?? config.confluence.spaceKey,
                                           ancestorsKey: ancestorsKey ?? config.confluence.ancestorsKey)
        
        var replacedTemplate = template
        parameter.templateAuguments.forEach { key, value in
            replacedTemplate = replacedTemplate.replacingOccurrences(of: "{{\(key)}}", with: value)
        }
        
        let page = Page(title: parameter.title, body: replacedTemplate, config: confluence)
        PageGenerator.generate(page: page, user: config.user)
    }
    
    public static func initialize() {
        let configDirName = ".coupage"
        let userConfigContents = "user:\n  id:\n  password:\n".data(using: .utf8)
        
        let userConfigFileName = "\(configDirName)/userConfig.yml"
        let templateDirName = "\(configDirName)/templates"
        
        let sampleDirName = "\(templateDirName)/sample"
        let sampleTmplFileName = "\(sampleDirName)/sample.tmpl"
        let sampleTmplContents = "<title>{{.title}}</title>".data(using: .utf8)
        let sampleYmlFileName = "\(sampleDirName)/sample.yml"
        let sampleYmlContents = "title: \"This page is generated by Coupage\"".data(using: .utf8)
        
        do {
            try FileManager.default.createDirectory(atPath: configDirName, withIntermediateDirectories: true, attributes: nil)
            _ = FileManager.default.createFile(atPath: userConfigFileName, contents: userConfigContents, attributes: nil)
            
            try FileManager.default.createDirectory(atPath: templateDirName, withIntermediateDirectories: true, attributes: nil)
            
            try FileManager.default.createDirectory(atPath: sampleDirName, withIntermediateDirectories: true, attributes: nil)
            
            _ = FileManager.default.createFile(atPath: sampleTmplFileName, contents: sampleTmplContents, attributes: nil)
            _ = FileManager.default.createFile(atPath: sampleYmlFileName, contents: sampleYmlContents, attributes: nil)
            
        } catch {
            try? FileManager.default.removeItem(atPath: configDirName)
            try? FileManager.default.removeItem(atPath: userConfigFileName)
            try? FileManager.default.removeItem(atPath: templateDirName)
            try? FileManager.default.removeItem(atPath: sampleDirName)
            try? FileManager.default.removeItem(atPath: sampleTmplFileName)
            try? FileManager.default.removeItem(atPath: sampleYmlFileName)
            fatalError("⛔️ failed to create config files")
        }
    }
}
